# Generated by Django 5.2.7 on 2025-10-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('proyector', 'Proyector'), ('Notebook', 'Impresora')], max_length=50)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('en reparacion', 'En Reparacion'), ('dado de baja', 'Dado de Baja')], default='operativo')),
                ('ubicacion', models.TextField(choices=[('sala de profesores', 'Sala de Profesores'), ('biblioteca', 'Biblioteca'), ('sala de computacion', 'Sala de Computacion')], max_length=100)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
